application:
  jwt:
    prefix: "Bearer "
    header: "Authorization"
    expires-at: 86400000
    secret: "_a_a!FZ&3!XZ93-+!?#nmEBY?DfS#H"
spring:
  datasource:
    url: jdbc:h2:mem:rabbitmq_user_db
    username: root
    password: root
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 8083